env:
  - DB=postgresql
  - DB=mysql
branches:
  except:
    - 'fit-pages'
rvm:
  - ree
services:
  - postgresql
  - mysql
before_script:
  - "cp config/database{.example,}.yml"
  - "bundle exec rake db:drop db:create db:schema:load"
script: "bundle exec rake spec"
