language: ruby
cache: bundler
bundler_args: --without development debug
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
branches:
  except:
    - fit-pages
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - "cp -v config/database.${DB}.yml config/database.yml"
  - "cp -v config/crewmate.example.yml config/crewmate.yml"
  - "bundle exec rake db:create db:schema:load RAILS_ENV=test"
script: "bundle exec rake spec cucumber"
matrix:
  allow_failures:
    - rvm: 2.0.0
addons:
  code_climate:
    repo_token: 74d9b568038c718984353cf6e8c54a8b151f87af24ae6eab5791bc2d00dc6211
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/66228b69038e52d1cbe1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
