language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
gemfile: Gemfile.
bundler_args: --without development
env:
  - DB=sqlite
  # - DB=postgres
  # - DB=mysql
before_script:
  - "cp config/database.${DB}.yml config/database.yml"
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
  - bundle exec rake db:test:prepare
matrix:
  allow_failures:
    - rvm: 1.9.3
