development:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: teambox2

test: &TEST
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: teambox2_test

production:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: teambox2_production

cucumber:
  <<: *TEST
